drivers: nq-nci: Fix -Wstrict-prototypes
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int lct_check_hwversion()

Signed-off-by: BladeRunner-A2C <john.smith@unused.email>